{% set name = "wfdb" %}
{% set version = "2.2.1" %}
{% set sha256 = "5225326103efde170b28884d85ee170dbc586c9fbaf0ae1a7126d66e1429677c" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python
    - setuptools
  run:
    - python
    - nose >=1.3.7
    - numpy >=1.11.0
    - matplotlib-base >=1.5.1
    - requests >=2.10.0
    - pandas >=0.19.1
    - scipy >=0.19.0
    - scikit-learn

test:
  imports:
    - wfdb
    - wfdb.plot
    - wfdb.processing
    - wfdb.io

about:
  home: https://github.com/MIT-LCP/wfdb-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The WFDB Python Toolbox
  description:
    Native python scripts for reading and writing WFDB signals and annotations.
  doc_url: https://github.com/MIT-LCP/wfdb-python
  dev_url: https://github.com/MIT-LCP/wfdb-python

extra:
  recipe-maintainers:
    - Gijom
