{% set name = "wfdb" %}
{% set version = "4.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MIT-LCP/{{ name }}-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c96c62b8abede8c0987c77d49285c923f114787a96d110cf95dac5e5d56360cd
  patches:
    # fix https://github.com/MIT-LCP/wfdb-python/pull/459
    - patches/0001_fix-numpy-valueerror.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  # pysoundfile not available for s390x or win
  skip: true  # [py<37 or s390x or win]

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - pip
    - poetry-core >=1.0.0
    - python
  run:
    - python
    - numpy >=1.10.1
    - scipy >=1.0.0
    - pandas >=1.3.0
    - pysoundfile >=0.10.0
    - matplotlib-base >=3.2.2
    - requests >=2.8.1

test:
  source_files:
    - tests
    - sample-data
  imports:
    - wfdb
    - wfdb.plot
    - wfdb.processing
    - wfdb.io
  requires:
    - pip
    - pytest
    - pytest-xdist >=2.5.0
  commands:
    - pip check
    - pytest -vv tests

about:
  home: https://github.com/MIT-LCP/wfdb-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The WFDB Python Toolbox
  description: Native python scripts for reading and writing WFDB signals and annotations.
  doc_url: https://wfdb.readthedocs.io
  dev_url: https://github.com/MIT-LCP/wfdb-python

extra:
  recipe-maintainers:
    - Gijom
