{% set name = "wfdb" %}
{% set version = "3.0.1" %}
{% set sha256 = "53d536bcc2b246edea3f9a724d2df5f4c7494b22947dcf4e2e92dcb50d81b5f4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - pip
    - python
    - setuptools
  run:
    - python
    - nose >=1.3.7
    - numpy >=1.11.0
    - matplotlib-base >=1.5.1
    - requests >=2.10.0
    - pandas >=0.19.1
    - scipy >=0.19.0
    - scikit-learn

test:
  imports:
    - wfdb
    - wfdb.plot
    - wfdb.processing
    - wfdb.io

about:
  home: https://github.com/MIT-LCP/wfdb-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The WFDB Python Toolbox
  description: Native python scripts for reading and writing WFDB signals and annotations.
  doc_url: https://github.com/MIT-LCP/wfdb-python
  dev_url: https://github.com/MIT-LCP/wfdb-python

extra:
  recipe-maintainers:
    - Gijom
