travis:
  secure:
    BINSTAR_TOKEN: ftEZk/X4i7WFtEY+JTwtACM1LG17LxJgc+XggmAUC6dMyzmpZ3HS0DyWcvr1eUEfhW/oIHHtYcgAn4m/c42a+gj3tOWCLjN/Hss03O8QJBxW1t4XbPLZKva9RGPdBzGLoCtqnetFtIzv6mQI+YcLLlz6xkBr2a/27ihJn6uAa3m3dCkSYcAbpCMq4lG7Zb4leQamkOLmjoe8xtDn3mo4DtBnpChTJLdseClK9jb6taWKrIv/1IzA0uuwGh0E0JzEozmEflPNybb/9GhFdRSLc0940OwSV6XYcFEBn+qhibSzTF8dIUEyqjK0eX/oNowBTR5Z/8QbbFNzx8yrwLG3j3PWQKIJQiNh+HaOstLSIhuI2ERz8KJvM1L9pXKZJSDAt5HW5LWFTIBvOJBDrdrQSIhfAbT5wTwkpfYgmEfrlgeOXOXXeP9MXCXjKHo2lF7SyYAmMN5KPLhDsfYbbMzHPn0KyaPsW03Z3rGatlTUus16KtAg+/jn4JAe7Eu58XNejQVynvhBUCTzjRJy4WRHfY+FsG9GX/2qUmmJOIZSVf2hSy66XFPKns3pgDK532/YjnqC+CZxzb5DrE3vV9Uj4aVTOQuL7rJsXcIq1AM81Je5qcXWrO3yhtam9weFvEKxLSEOEzpxQlWmw5+wyzfUYeQTCY1Xmv5D4flV143Bh4o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
