travis:
  secure:
    BINSTAR_TOKEN: ne6Oz/Ws05kPTE6nfSpLP7r6UX1lO2Edhwl9qDPy2aadLfgF6by0cHXgYmiNlmSl0fF+D2XtaYgx/yBoNz7E749tzQz+er01w9xvpTVvdGwc1K8MpV7A2cpABkoOAOQx90adQcYt4ljRPcETMTlrrlStFJSl3jt5G/2Av9Qu+boVqFLFgsvBNjYq5Qflr8FqlsuP/Fih2P/LZt8FvM9/VfY8M4NJUWo9mIPAeZRzPKQ9If3JcxOAXOq70Nk1O+RkRN+K9qNhXqJK+RS1XRRit6i496RB7m0mSnQ2bPzkXK0nLGyAweJDTtbDTWAOhiYu7Fqg+V44aDNOLroiLJobM05oVArRSg5dseG77cIukQiKficSdCRqiRrT8pODufHthGWzAP9BKqSypdbGr5GBCAFiEwytsUokEOrIHZ5o53A4p/ndLnuSyW4wo+s/fpvma0di0zmydRNyjoLyRqcwktAwlhsaBy0kPoOmnZP4eG5FutXEVzFKnKmWbhlxUmXBsKLXmKiek9jaIkExPsjnpjy7acNH5lTh3BVuwt/ccrZ6nIhz9jyZMhXfOiZpym3/vTdquTL7DiAWme/BzCTIFY+zRw/xTvG8Hysk7W7Y+tF3DJTcxrP2PnmuFmtoJdn6lZPvykpBSfPo747mP7qnFRyJyhZXUp7j5CN8tM5nEGk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
